### ISSUE TITLE
enum The

### ISSUE THREAD

**Issue by AlexShkor** [MSayfullin/FluentStrings#1]
Удалите пожалуйста enum The. Сделайте нормальное имя в ущерб удобочитаемости цепочки вызовов Fluent actions.
А потом просто добавьте еще несколько Fluent методов тип  ###.From().TheEnd(), ###.From().TheBegining()

**Comment by MSayfullin** [comment]
1. Если удалить enum The, увеличится общая сложность всего интерфейса.
2. Кроме этого, не понятна логика метода ###.From() Что он будет возвращать, если после него не будет вызова метода TheEnd() или TheBeginning()?

Готов рассмотреть ваш pull request с возвожным решением этой проблемы.
