### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by devmondo** [MSayfullin/FluentStrings#2]
hi, 
awesome library, can i use it instead of stringbuilder when using Insert method ?

another question is how can we combine IndexOf and Remove to simulate c# SubString()?

thanks in advanced.

**Comment by MSayfullin** [comment]
Hi,
maybe I didn't get you right, but for time being it is not possible to use `StringBuilder` as a source for transformations. Unless you call `ToString` method on it. But this could be possibly a performance issue.
If you talk about internals, `StringBuilder` is already used inside.

**Comment by MSayfullin** [comment]
As for your second question, many things are planned. To understand exactly what you need, could you, please, give an example?

**Comment by devmondo** [comment]
hi, 
thanks for the reply, the first question is answered and it is great that stringbuilder is used internally :)

as for second question what i meant is if i have string like this 
" this is a test string" 
and i want to remove all text after "is" so i can get "a test string" 
or remove everything before "test" so i can get "test string"

thanks in advanced.

**Comment by MSayfullin** [comment]
Now I see. Yes this is planned also.
If you need this ASAP just let me know, I'll try to prioritize it.

**Comment by devmondo** [comment]
thanks a lot, i think this is very important, as a lot of my code and many others is based on substring, which is not to intuitive, and if you prioritize it it would be great, also if you can put road-map in your git hub page it would be nice so we can interact with you better.

thanks a lot again for listening :)

**Comment by MSayfullin** [comment]
You're welcome.

Finally, I've fixed some bugs and started to implement your request. I'm planning to finish it in week or two. Hope this won't be an issue for you.

As for roadmap, it looks like a good idea, I'll try to put this when I have time.

**Comment by devmondo** [comment]
man, i should thank you, i am sitting here on my chair and asking for things while you are generously listening to it and adding it without return :)

take your time mate, and thanks in advanced for any implementation, and i would like to bring your attention to this library as it might help you as well
http://matchkit.codeplex.com/

i am planning to use your plugin as an all in all string manipulation tool because it looks neater, so my humble advise if you can also add extensibility point, where one can add to this library through an Interface or something similar :)

**Comment by MSayfullin** [comment]
I've heard it is called Open Source :)

There are some extensibility points and aliases are planned and I will describe them in roadmap or in a wiki. But there is no need for waiting them, because you can extend string itself at any time :)

Have a good time and thanks for a link!

**Comment by devmondo** [comment]
awesome man, 
thank you for your support and have a good time too :)

**Comment by MSayfullin** [comment]
Sorry, it took a bit longer and not everything I wanted is implemented, but here it is. You can already use next actions.

To remove starting to some indexes in a string:

``` csharp
"some string".Remove().Starting(position: 3).From(The.End).To(position: 2).From(The.Beginning);
```

To remove starting some marker:

``` csharp
"some string".Remove().Starting(1, of: "some").IgnoringCase().From(The.End);
```

And to remove up to some marker as well:

``` csharp
"some string".Remove().To(The.EndOf, 1, of: "some").From(The.End);
```

Different combinations of Starting-To action is on the way.

**Comment by devmondo** [comment]
this is awesome, thanks a lot for not forgetting, i love your work on this. all the best :)
